name: Generate Snake Game

on:
  schedule:
    - cron: '36 21 * * *'  # Executa todos os dias à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Snake Game
      uses: Platane/snk@master
      with:
        github_user_name: michelmartinss
        svg_out_path: dist/github-contribution-grid-snake.svg

    - uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
